apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creators
  namespace: shipping-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-creator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: bob@foo-corp.com
