apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fulfillmentcenters.foo-corp.com
spec:
  group: foo-corp.com
  names:
    kind: FulfillmentCenter
    plural: fulfillmentcenters
    singular: fulfillmentcenter
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            address:
              type: string
          required:
          - address
          type: object
  versions:
  - name: v1
    served: true
    storage: false
  - name: v2
    served: true
    storage: true
