apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
  namespace: shipping-dev
rules:
- apiGroups:
  - batch/v1
  resources:
  - jobs
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creators
  namespace: shipping-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-creator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sam@foo-corp.com
