# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

run:
  deadline: 5m
  skip-dirs:
    - yaml/internal/k8sgen/pkg

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    # - dogsled # uncomment after upgrading golangci-lint (Issue #3663)
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
#    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    # - whitespace # uncomment after upgrading golangci-lint (Issue #3663)


linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170
  gocyclo:
    min-complexity: 30
  golint:
    min-confidence: 0.85
