# Copyright 2026 The kpt Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 17 * * *'

jobs:
  shell-ci:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - name: Lint shell scripts, ignoring third-party files
      run: |
        find . -name "*.sh" | grep -v site | grep -v vendor | grep -v node_modules | grep -v demo/demo-magic > shell_files.out
        shellcheck $(cat shell_files.out)  

  go-ci:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Go
      uses: kptdev/kpt/.github/actions/setup-go-kpt@main
      with:
        go-version-file: go/get-started/go.mod
        install-kpt: 'false'
        cache-dependency-path: go/**/go.sum
    - name: Build, Test, Lint
      run: hack/ci-validate-go.sh