name: mirror-functions

on:
  push:
    branches:roufique_pitch-1
      - "master"
  schedule:
    - cron: "0 18 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "275.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker
      - name: Mirror images
        run: |
          ./scripts/mirrorImages.sh
