name: release-create-kpt-functions

on:
  push:
    tags:
      - release-create-kpt-functions-*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/kpt-functions-sdk/go
      GO111MODULE: off
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into GOPATH
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/${{ github.repository }}
    - name: Build, Test, Lint
      run: |
        cd go
        make package-typegen
    - name: Set up gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '275.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Upload binaries
      run: ./scripts/publish-bins.sh $GITHUB_REF
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://wombat-dressing-room.appspot.com'
    - name: Install, test
      run: |
        cd ts/create-kpt-functions
        npm ci
        npm test
    - name: Publish
      run: |
        cd ts/create-kpt-functions
        ../../scripts/publish-npm.sh $GITHUB_REF
      env:
        NODE_AUTH_TOKEN: ${{ secrets.WOMBAT_CREATE_KPT_FUNCTIONS }}
