name: release-gatekeeper-function

on:
  push:
    tags:
      - release-gatekeeper-function-*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/kpt-functions-sdk/go
      GO111MODULE: off
    steps:
    - name: Set up gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '275.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into GOPATH
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/${{ github.repository }}
    - name: Build, Test, Lint
      run: |
        cd go
        make all
    - name: Push to container registry
      run: |
        cd go
        TAG=latest ./scripts/publish-functions.sh