name: release-ts-kpt-functions

on:
  push:
    tags:
      - release-ts-kpt-functions-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: 'https://wombat-dressing-room.appspot.com'
    - name: Install, test
      run: |
        cd ts/kpt-functions
        npm ci
        npm test
    - name: Publish
      run: |
        cd ts/kpt-functions
        ../scripts/publish-npm.sh $GITHUB_REF
      env:
        NODE_AUTH_TOKEN: ${{ secrets.WOMBAT_KPT_FUNCTIONS }}
