name: release-typegen

on:
  push:
    tags:
      - release-typegen-*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/kpt-functions-sdk/ts/typegen
      GO111MODULE: on
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Check out code into GOPATH
        uses: actions/checkout@v1
        with:
          path: go/src/github.com/GoogleContainerTools/kpt-functions-sdk
      - name: Build, Test, Lint
        run: |
          cd ts/typegen
          make package-typegen
      - name: Set up gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.6.0
        with:
          version: '388.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Upload binaries
        run: ./ts/scripts/publish-bins.sh $GITHUB_REF
