name: release-typegen

on:
  push:
    tags:
      - release-typegen-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build, Test, Lint
        run: |
          cd ts/typegen
          make package-typegen
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Upload binaries
        run: ./ts/scripts/publish-bins.sh $GITHUB_REF
